/**
 * Data Fixtures for QUẢN LÝ ĐẢNG VIÊN KHCB
 * Chỉ chứa dữ liệu tham chiếu (danh mục) và tài khoản người dùng thật.
 * Các danh sách nghiệp vụ (đảng viên, hồ sơ...) để trống - dữ liệu thật sẽ
 * được nhập trực tiếp bởi người dùng và đồng bộ qua Firebase Firestore.
 */

import {
    PartyMember,
    ForeignTrip,
    DevelopmentCandidate,
    AdmissionDossier,
    OfficializationDossier,
    PolicyVersion,
    DocumentTemplate,
    UserAccount,
    AuditLog,
    MemberChangeRequest,
    RefItem,
    ProvinceItem,
} from '../types';

export const INITIAL_REF_COUNTRIES: RefItem[] = [
  { id: '1', code: 'VN', name: 'Việt Nam' },
  { id: '2', code: 'JP', name: 'Nhật Bản' },
  { id: '3', code: 'US', name: 'Hoa Kỳ' },
  { id: '4', code: 'KR', name: 'Hàn Quốc' },
  { id: '5', code: 'FR', name: 'Pháp' },
  { id: '6', code: 'DE', name: 'Đức' },
  { id: '7', code: 'AU', name: 'Úc' },
  { id: '8', code: 'SG', name: 'Singapore' },
  { id: '9', code: 'GB', name: 'Anh' },
  ];

export const INITIAL_REF_PROVINCES: ProvinceItem[] = [
  { id: '1', code: 'CTO', name: 'Cần Thơ' },
  { id: '2', code: 'HCM', name: 'TP. Hồ Chí Minh' },
  { id: '3', code: 'HNO', name: 'Hà Nội' },
  { id: '4', code: 'DNA', name: 'Đà Nẵng' },
  { id: '5', code: 'AGI', name: 'An Giang' },
  { id: '6', code: 'DTH', name: 'Đồng Tháp' },
  { id: '7', code: 'VLO', name: 'Vĩnh Long' },
  { id: '8', code: 'HGI', name: 'Hậu Giang' },
  { id: '9', code: 'STR', name: 'Sóc Trăng' },
  { id: '10', code: 'CMA', name: 'Cà Mau' },
  ];

export const INITIAL_REF_ETHNICITIES: RefItem[] = [
  { id: '1', code: 'KINH', name: 'Kinh' },
  { id: '2', code: 'TAY', name: 'Tày' },
  { id: '3', code: 'THAI', name: 'Thái' },
  { id: '4', code: 'MUONG', name: 'Mường' },
  { id: '5', code: 'KHMER', name: 'Khơ-me' },
  { id: '6', code: 'HOA', name: 'Hoa' },
  ];

export const INITIAL_REF_RELIGIONS: RefItem[] = [
  { id: '1', code: 'NONE', name: 'Không' },
  { id: '2', code: 'PHAT', name: 'Phật giáo' },
  { id: '3', code: 'CONG', name: 'Công giáo' },
  { id: '4', code: 'HOAHAO', name: 'Hòa Hảo' },
  { id: '5', code: 'CAODAI', name: 'Cao Đài' },
  { id: '6', code: 'TINLANH', name: 'Tin Lành' },
  ];

// Danh sách Đảng viên - Để trống, nhập dữ liệu thật qua giao diện hoặc Nhập Excel
export const INITIAL_PARTY_MEMBERS: PartyMember[] = [];

// Danh sách chuyến đi nước ngoài - Để trống, nhập dữ liệu thật
export const INITIAL_FOREIGN_TRIPS: ForeignTrip[] = [];

// Danh sách nguồn phát triển Đảng - Để trống, nhập dữ liệu thật
export const INITIAL_DEVELOPMENT_CANDIDATES: DevelopmentCandidate[] = [];

export const INITIAL_POLICY_VERSIONS: PolicyVersion[] = [
  {
        id: 'pv-01',
        code: '01-HD/TW',
        name: 'Hướng dẫn 01-HD/TW ngày 19/05/2026',
        status: 'CURRENT_ACTIVE',
        effectiveDate: '19/05/2026',
        confirmedByAdmin: true,
        confirmedAt: '2026-05-20T08:00:00Z',
        itemsConfig: [
          {
                    code: 'A1',
                    order: 1,
                    group: 'GROUP_A',
                    name: 'Đơn xin vào Đảng',
                    description: 'Viết tay, trình bày rõ nhận thức về Đảng và động cơ vào Đảng',
                    mandatory: true,
          },
          {
                    code: 'A2',
                    order: 2,
                    group: 'GROUP_A',
                    name: 'Lý lịch của người xin vào Đảng',
                    description: 'Kê khai trung thực, đầy đủ theo mẫu 2-KNĐ, có xác minh cấp ủy',
                    mandatory: true,
          },
          {
                    code: 'A3',
                    order: 3,
                    group: 'GROUP_A',
                    name: 'Giấy chứng nhận hoàn thành lớp bồi dưỡng nhận thức về Đảng',
                    description: 'Bản chính do Trung tâm chính trị / Đảng ủy cơ sở cấp',
                    mandatory: true,
          },
          {
                    code: 'B1',
                    order: 4,
                    group: 'GROUP_B',
                    name: 'Bản nhận xét của đoàn thể nơi công tác (Công đoàn / Đoàn Thanh niên)',
                    description: 'Nhận xét ưu khuyết điểm và kiến nghị của đoàn thể',
                    mandatory: true,
          },
          {
                    code: 'B2',
                    order: 5,
                    group: 'GROUP_B',
                    name: 'Phiếu lấy ý kiến nhận xét của chi ủy / nhân dân nơi cư trú',
                    description: 'Mẫu 3-KNĐ lấy ý kiến nơi cư trú theo quy định',
                    mandatory: true,
          },
          {
                    code: 'B3',
                    order: 6,
                    group: 'GROUP_B',
                    name: 'Giấy giới thiệu của 02 đảng viên chính thức được phân công giúp đỡ',
                    description: 'Bản nhận xét và giới thiệu của người hướng dẫn 1 và người hướng dẫn 2',
                    mandatory: true,
          },
          {
                    code: 'C1',
                    order: 7,
                    group: 'GROUP_C',
                    name: 'Nghị quyết giới thiệu đoàn viên ưu tú vào Đảng của Đoàn Thanh niên',
                    description: 'Nếu người xin vào Đảng trong độ tuổi đoàn viên',
                    mandatory: false,
          },
          {
                    code: 'C2',
                    order: 8,
                    group: 'GROUP_C',
                    name: 'Nghị quyết đề nghị kết nạp đảng viên của Chi bộ',
                    description: 'Được biểu quyết tại kỳ họp chi bộ đạt từ 2/3 trở lên',
                    mandatory: true,
          },
          {
                    code: 'C3',
                    order: 9,
                    group: 'GROUP_C',
                    name: 'Kết luận thẩm định tiêu chuẩn chính trị của cấp ủy có thẩm quyền',
                    description: 'Kết luận tiêu chuẩn chính trị phục vụ kết nạp Đảng',
                    mandatory: true,
          },
              ],
  },
  {
        id: 'pv-208',
        code: '208-QĐ/TW',
        name: 'Quy định 208-QĐ/TW ngày 26/07/2026',
        status: 'CURRENT_ACTIVE',
        effectiveDate: '26/07/2026',
        confirmedByAdmin: true,
        confirmedAt: '2026-07-27T08:00:00Z',
        itemsConfig: [
          {
                    code: 'OFF-1',
                    order: 1,
                    group: 'OFFICIAL_ITEM',
                    name: 'Giấy chứng nhận học lớp bồi dưỡng đảng viên mới',
                    description: 'Do Đảng ủy cơ sở cấp sau thời gian dự bị',
                    mandatory: true,
          },
          {
                    code: 'OFF-2',
                    order: 2,
                    group: 'OFFICIAL_ITEM',
                    name: 'Bản tự kiểm điểm của đảng viên dự bị',
                    description: 'Tự đánh giá kết quả rèn luyện trong 12 tháng dự bị',
                    mandatory: true,
          },
          {
                    code: 'OFF-3',
                    order: 3,
                    group: 'OFFICIAL_ITEM',
                    name: 'Bản nhận xét về đảng viên dự bị của đảng viên chính thức hướng dẫn',
                    description: 'Nhận xét của đảng viên hướng dẫn về quá trình dự bị',
                    mandatory: true,
          },
          {
                    code: 'OFF-4',
                    order: 4,
                    group: 'OFFICIAL_ITEM',
                    name: 'Bản tổng hợp nhận xét của đoàn thể nơi làm việc và chi ủy nơi cư trú',
                    description: 'Tổng hợp ý kiến các đoàn thể và chi ủy nơi cư trú',
                    mandatory: true,
          },
          {
                    code: 'OFF-5.1',
                    order: 5,
                    group: 'OFFICIAL_ITEM',
                    name: 'Nghị quyết đề nghị công nhận đảng viên chính thức của Chi bộ',
                    description: 'Nghị quyết chi bộ thông qua biểu quyết',
                    mandatory: true,
          },
          {
                    code: 'OFF-5.2',
                    order: 6,
                    group: 'OFFICIAL_ITEM',
                    name: 'Nghị quyết của Đảng ủy cơ sở / Bộ phận',
                    description: 'Nghị quyết cấp ủy cơ sở',
                    mandatory: true,
          },
          {
                    code: 'OFF-5.3',
                    order: 7,
                    group: 'OFFICIAL_ITEM',
                    name: 'Quyết định công nhận đảng viên chính thức của cấp ủy có thẩm quyền',
                    description: 'Quyết định do Ban Thường vụ Đảng ủy ban hành',
                    mandatory: true,
          },
          {
                    code: 'OFF-5.4',
                    order: 8,
                    group: 'OFFICIAL_ITEM',
                    name: 'Biên bản công bố quyết định tại kỳ sinh hoạt Chi bộ',
                    description: 'Theo dõi ngày công bố quyết định',
                    mandatory: true,
          },
              ],
  },
  {
        id: 'pv-06',
        code: '06-HD/TW',
        name: 'Hướng dẫn 06-HD/TW ngày 09/06/2025',
        status: 'REPLACED_HISTORICAL',
        replacedHistoryNote: 'Đã được thay thế bởi Hướng dẫn 01-HD/TW ngày 19/05/2026. Lưu tham chiếu lịch sử.',
        effectiveDate: '09/06/2025',
        confirmedByAdmin: true,
        confirmedAt: '2025-06-10T08:00:00Z',
        itemsConfig: [],
  },
  ];

// Danh sách hồ sơ kết nạp Đảng - Để trống, nhập dữ liệu thật
export const INITIAL_ADMISSION_DOSSIERS: AdmissionDossier[] = [];

// Danh sách hồ sơ công nhận chính thức - Để trống, nhập dữ liệu thật
export const INITIAL_OFFICIALIZATION_DOSSIERS: OfficializationDossier[] = [];

// Danh sách yêu cầu thay đổi hồ sơ - Để trống, nhập dữ liệu thật
export const INITIAL_CHANGE_REQUESTS: MemberChangeRequest[] = [];

export const INITIAL_USER_ACCOUNTS: UserAccount[] = [
  {
        uid: 'uid-admin-system',
        email: 'chibokhcb@ctump.edu.vn',
        fullName: 'BÍ THƯ CHI BỘ (QUẢN TRỊ HỆ THỐNG)',
        role: 'SUPER_ADMIN',
        positionTitle: 'Bí thư Chi bộ / Email Quản trị',
        staffCode: '001000',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        approvalNotes: 'Quản trị hệ thống toàn quyền',
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-bi-thu-tram',
        email: 'ntttram@ctump.edu.vn',
        fullName: 'NGUYỄN THỊ THU TRÂM',
        role: 'SUPER_ADMIN',
        positionTitle: 'Bí thư Chi bộ',
        staffCode: '001001',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        approvalNotes: 'Quản trị tất cả (Toàn quyền Bí thư)',
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pho-bi-thu-hung',
        email: 'nthung@ctump.edu.vn',
        fullName: 'NGUYỄN THANH HÙNG',
        role: 'SUPER_ADMIN',
        positionTitle: 'Phó Bí thư Chi bộ',
        staffCode: '001002',
        status: 'ACTIVE',
        requiresSecretaryApproval: true,
        approvalNotes: 'Được điều chỉnh hệ thống nhưng hiển thị trạng thái "Cần Bí thư phê duyệt"',
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-chi-uy-vien-le',
        email: 'letran@ctump.edu.vn',
        fullName: 'TRẦN THỊ HỒNG LÊ',
        role: 'SUPER_ADMIN',
        positionTitle: 'Chi ủy viên',
        staffCode: '001003',
        status: 'ACTIVE',
        requiresSecretaryApproval: true,
        approvalNotes: 'Được điều chỉnh hệ thống nhưng hiển thị trạng thái "Cần Bí thư phê duyệt"',
        createdAt: '2026-01-01T00:00:00Z',
  },
    // Danh sách Đảng viên Chi bộ Khoa học cơ bản (25 Đảng viên)
  {
        uid: 'uid-pm-nttminh',
        email: 'nttminh@ctump.edu.vn',
        fullName: 'NGUYỄN THỊ TUYẾT MINH',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001005',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-lttmy',
        email: 'lttmy@ctump.edu.vn',
        fullName: 'LÝ THỊ TRÀ MY',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001006',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nlmdang',
        email: 'nlmdang@ctump.edu.vn',
        fullName: 'NGUYỄN LÂM MINH ĐĂNG',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001007',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-tttchau',
        email: 'tttchau@ctump.edu.vn',
        fullName: 'TRƯƠNG THỊ TUYẾT CHÂU',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001008',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nptai',
        email: 'nptai@ctump.edu.vn',
        fullName: 'NGUYỄN PHƯỚC TÀI',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001009',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-ptnnga',
        email: 'ptnnga@ctump.edu.vn',
        fullName: 'PHẠM THỊ NGỌC NGA',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001010',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-ltttien',
        email: 'ltttien@ctump.edu.vn',
        fullName: 'LÂM THỊ THỦY TIÊN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001011',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-cmkhoa',
        email: 'cmkhoa@ctump.edu.vn',
        fullName: 'CHÂU MINH KHOA',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001012',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-lththanh',
        email: 'lththanh@ctump.edu.vn',
        fullName: 'LƯƠNG THỊ HOÀI THANH',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001013',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nhthai',
        email: 'nhthai@ctump.edu.vn',
        fullName: 'NGUYỄN HOÀNG THÁI',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001014',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-axsam',
        email: 'axsam@ctump.edu.vn',
        fullName: 'ÂU XUÂN SÂM',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001015',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-dqthanh',
        email: 'dqthanh@ctump.edu.vn',
        fullName: 'DƯƠNG QUỐC THANH',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001016',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-dtttran',
        email: 'dtttran@ctump.edu.vn',
        fullName: 'ĐOÀN THỊ THÙY TRÂN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001017',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nxvinh',
        email: 'nxvinh@ctump.edu.vn',
        fullName: 'NGUYỄN XUÂN VINH',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001018',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-dntruong',
        email: 'dntruong@ctump.edu.vn',
        fullName: 'ĐINH NGỌC TRƯỜNG',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001019',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nnuyen',
        email: 'nnuyen@ctump.edu.vn',
        fullName: 'NGÔ NGỌC UYÊN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001020',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-vttrinh',
        email: 'vttrinh@ctump.edu.vn',
        fullName: 'VÕ THÀNH TRINH',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001021',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-lmthuan',
        email: '2453110046@student.ctump.edu.vn',
        fullName: 'LÊ MINH THUẬN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên / Sinh viên',
        staffCode: '2453110046',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-dntdat',
        email: '2453110009@student.ctump.edu.vn',
        fullName: 'ĐỖ NGUYỄN TIẾN ĐẠT',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên / Sinh viên',
        staffCode: '2453110009',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-lmnhan',
        email: 'lmnhan@ctump.edu.vn',
        fullName: 'LÊ MINH NHÂN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001024',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nhmen',
        email: 'nhmen@ctump.edu.vn',
        fullName: 'NGUYỄN HOÀNG MẾN',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001025',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-dntduong',
        email: '2553110010@student.ctump.edu.vn',
        fullName: 'DƯƠNG NGỌC THÙY DƯƠNG',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên / Sinh viên',
        staffCode: '2553110010',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-ltnhi',
        email: 'ltnhi@ctump.edu.vn',
        fullName: 'LÝ TUYẾT NHI',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001027',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-ltde',
        email: 'ltde@ctump.edu.vn',
        fullName: 'LÊ TIỀN ĐỀ',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001028',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  {
        uid: 'uid-pm-nhpdai',
        email: 'nhpdai@ctump.edu.vn',
        fullName: 'NGUYỄN HỮU PHƯỚC ĐẠI',
        role: 'PARTY_MEMBER',
        positionTitle: 'Đảng viên',
        staffCode: '001029',
        status: 'ACTIVE',
        requiresSecretaryApproval: false,
        createdAt: '2026-01-01T00:00:00Z',
  },
  ];

// Nhật ký hệ thống - Để trống, sẽ được ghi tự động khi có thao tác thật
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];

export const INITIAL_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
        id: 'tmpl-01',
        templateCode: 'MAU-01-KND',
        title: 'Đơn xin vào Đảng (Viết tay mẫu)',
        category: 'Kết nạp Đảng',
        policyVersionId: 'pv-01',
        fileUrl: '#',
        originalName: 'Don_xin_vao_Dang_Mau_2026.docx',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        version: 1,
        isActive: true,
        uploadedAt: '2026-01-10T08:00:00Z',
  },
  {
        id: 'tmpl-02',
        templateCode: 'MAU-02-KND',
        title: 'Lý lịch của người xin vào Đảng',
        category: 'Kết nạp Đảng',
        policyVersionId: 'pv-01',
        fileUrl: '#',
        originalName: 'Ly_lich_nguoi_xin_vao_Dang_Mau_2026.docx',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        version: 1,
        isActive: true,
        uploadedAt: '2026-01-10T08:00:00Z',
  },
  {
        id: 'tmpl-03',
        templateCode: 'MAU-03-OFF',
        title: 'Bản tự kiểm điểm đảng viên dự bị',
        category: 'Công nhận chính thức',
        policyVersionId: 'pv-208',
        fileUrl: '#',
        originalName: 'Ban_tu_kiem_diem_dang_vien_du_bi.docx',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        version: 1,
        isActive: true,
        uploadedAt: '2026-01-10T08:00:00Z',
  },
  ];
