/**
 * Anonymous Demo Data Fixtures for QUẢN LÝ ĐẢNG VIÊN KHCB
 * Adheres strictly to anonymity requirements with 6 model members.
 */

import {
  PartyMember,
  ForeignTrip,
  DevelopmentCandidate,
  AdmissionDossier,
  OfficializationDossier,
  PolicyVersion,
  DocumentTemplate,
  UserAccount,
  AuditLog,
  MemberChangeRequest,
  RefItem,
  ProvinceItem,
} from '../types';

export const INITIAL_REF_COUNTRIES: RefItem[] = [
  { id: '1', code: 'VN', name: 'Việt Nam' },
  { id: '2', code: 'JP', name: 'Nhật Bản' },
  { id: '3', code: 'US', name: 'Hoa Kỳ' },
  { id: '4', code: 'KR', name: 'Hàn Quốc' },
  { id: '5', code: 'FR', name: 'Pháp' },
  { id: '6', code: 'DE', name: 'Đức' },
  { id: '7', code: 'AU', name: 'Úc' },
  { id: '8', code: 'SG', name: 'Singapore' },
  { id: '9', code: 'GB', name: 'Anh' },
];

export const INITIAL_REF_PROVINCES: ProvinceItem[] = [
  { id: '1', code: 'CTO', name: 'Cần Thơ' },
  { id: '2', code: 'HCM', name: 'TP. Hồ Chí Minh' },
  { id: '3', code: 'HNO', name: 'Hà Nội' },
  { id: '4', code: 'DNA', name: 'Đà Nẵng' },
  { id: '5', code: 'AGI', name: 'An Giang' },
  { id: '6', code: 'DTH', name: 'Đồng Tháp' },
  { id: '7', code: 'VLO', name: 'Vĩnh Long' },
  { id: '8', code: 'HGI', name: 'Hậu Giang' },
  { id: '9', code: 'STR', name: 'Sóc Trăng' },
  { id: '10', code: 'CMA', name: 'Cà Mau' },
];

export const INITIAL_REF_ETHNICITIES: RefItem[] = [
  { id: '1', code: 'KINH', name: 'Kinh' },
  { id: '2', code: 'TAY', name: 'Tày' },
  { id: '3', code: 'THAI', name: 'Thái' },
  { id: '4', code: 'MUONG', name: 'Mường' },
  { id: '5', code: 'KHMER', name: 'Khơ-me' },
  { id: '6', code: 'HOA', name: 'Hoa' },
];

export const INITIAL_REF_RELIGIONS: RefItem[] = [
  { id: '1', code: 'NONE', name: 'Không' },
  { id: '2', code: 'PHAT', name: 'Phật giáo' },
  { id: '3', code: 'CONG', name: 'Công giáo' },
  { id: '4', code: 'HOAHAO', name: 'Hòa Hảo' },
  { id: '5', code: 'CAODAI', name: 'Cao Đài' },
  { id: '6', code: 'TINLANH', name: 'Tin Lành' },
];

export const INITIAL_PARTY_MEMBERS: PartyMember[] = [
  {
    id: 'pm-000',
    stt: 1,
    fullName: 'BÍ THƯ CHI BỘ (QUẢN TRỊ HỆ THỐNG)',
    normalizedName: 'bi thu chi bo quan tri he thong',
    otherName: 'Chi bộ KHCB',
    gender: 'Nam',
    dateOfBirth: '15/08/1978',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089078000000',
    partyCardNumber: '370123000000',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '03/02/2005',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Quận Ninh Kiều' },
    hometown: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Quận Ninh Kiều' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Khánh' },
    partyAdmissionDate: '19/05/2005',
    officialPartyDate: '19/05/2006',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Tài khoản Quản trị hệ thống Chi bộ KHCB',
    staffCode: '001000',
    workEmail: 'chibokhcb@ctump.edu.vn',
    phone: '0901000000',
    department: 'Chi bộ Khoa học cơ bản',
    academicTitle: 'Tiến sĩ, Giảng viên chính',
    jobTitle: 'Bí thư Chi bộ',
    userUid: 'uid-admin-system',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-001',
    stt: 2,
    fullName: 'NGUYỄN THỊ THU TRÂM',
    normalizedName: 'nguyen thi thu tram',
    otherName: 'Thu Trâm',
    gender: 'Nữ',
    dateOfBirth: '12/04/1981',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089081001001',
    partyCardNumber: '370123450001',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '03/02/2008',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Quận Ninh Kiều' },
    hometown: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Quận Bình Thủy' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Khánh' },
    partyAdmissionDate: '19/05/2006',
    officialPartyDate: '19/05/2007',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Hồ sơ đầy đủ, Bí thư Chi bộ',
    staffCode: '001001',
    workEmail: 'ntttram@ctump.edu.vn',
    phone: '0901000001',
    department: 'Bộ môn Toán - Tin',
    academicTitle: 'Tiến sĩ, Giảng viên chính',
    jobTitle: 'Bí thư Chi bộ',
    userUid: 'uid-bi-thu-tram',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-002',
    stt: 3,
    fullName: 'NGUYỄN THANH HÙNG',
    normalizedName: 'nguyen thanh hung',
    otherName: 'Thanh Hùng',
    gender: 'Nam',
    dateOfBirth: '20/11/1983',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089083002002',
    partyCardNumber: '370123450002',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '19/05/2010',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'An Giang', detail: 'TP. Long Xuyên' },
    hometown: { country: 'Việt Nam', province: 'An Giang', detail: 'Chợ Mới' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Xuân Khánh' },
    partyAdmissionDate: '02/09/2008',
    officialPartyDate: '02/09/2009',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Hồ sơ đầy đủ, Phó Bí thư',
    staffCode: '001002',
    workEmail: 'nthung@ctump.edu.vn',
    phone: '0901000002',
    department: 'Bộ môn Lý luận chính trị',
    academicTitle: 'Thạc sĩ, Giảng viên chính',
    jobTitle: 'Phó Bí thư Chi bộ',
    userUid: 'uid-pho-bi-thu-hung',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-003',
    stt: 4,
    fullName: 'TRẦN THỊ HỒNG LÊ',
    normalizedName: 'tran thi hong le',
    otherName: 'Hồng Lê',
    gender: 'Nữ',
    dateOfBirth: '10/02/1985',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089085003003',
    partyCardNumber: '370123450003',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '03/02/2012',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Vĩnh Long', detail: 'TP. Vĩnh Long' },
    hometown: { country: 'Việt Nam', province: 'Vĩnh Long', detail: 'Bình Minh' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Hưng Lợi' },
    partyAdmissionDate: '03/02/2010',
    officialPartyDate: '03/02/2011',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Hồ sơ đầy đủ, Chi ủy viên',
    staffCode: '001003',
    workEmail: 'letran@ctump.edu.vn',
    phone: '0901000003',
    department: 'Bộ môn Ngoại ngữ',
    academicTitle: 'Thạc sĩ, Giảng viên',
    jobTitle: 'Chi ủy viên',
    userUid: 'uid-chi-uy-vien-le',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-005',
    stt: 5,
    fullName: 'NGUYỄN THỊ TUYẾT MINH',
    normalizedName: 'nguyen thi tuyet minh',
    gender: 'Nữ',
    dateOfBirth: '25/04/1988',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089088005005',
    partyCardNumber: '370123450005',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Đồng Tháp', detail: 'TP. Cao Lãnh' },
    hometown: { country: 'Việt Nam', province: 'Đồng Tháp', detail: 'Sa Đéc' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Hòa' },
    partyAdmissionDate: '26/03/2015',
    officialPartyDate: '26/03/2016',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Đảng viên chính thức',
    staffCode: '001005',
    workEmail: 'nttminh@ctump.edu.vn',
    phone: '0901000005',
    department: 'Bộ môn Vật lý Y sinh',
    academicTitle: 'Thạc sĩ, Giảng viên',
    jobTitle: 'Giảng viên',
    userUid: 'uid-pm-nttminh',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-006',
    stt: 6,
    fullName: 'LÝ THỊ TRÀ MY',
    normalizedName: 'ly thi tra my',
    gender: 'Nữ',
    dateOfBirth: '14/09/1990',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089090006006',
    partyCardNumber: '370123450006',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Sóc Trăng', detail: 'TP. Sóc Trăng' },
    hometown: { country: 'Việt Nam', province: 'Sóc Trăng', detail: 'Mỹ Xuyên' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Khánh' },
    partyAdmissionDate: '19/05/2017',
    officialPartyDate: '19/05/2018',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Đảng viên chính thức',
    staffCode: '001006',
    workEmail: 'lttmy@ctump.edu.vn',
    phone: '0901000006',
    department: 'Bộ môn Hóa học Y học',
    academicTitle: 'Thạc sĩ, Giảng viên',
    jobTitle: 'Giảng viên',
    userUid: 'uid-pm-lttmy',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-003',
    stt: 3,
    fullName: 'ĐẢNG VIÊN MẪU 03',
    normalizedName: 'dang vien mau 03',
    gender: 'Nam',
    dateOfBirth: '10/02/1988',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089088003003',
    partyCardNumber: '370123450003',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '03/02/2016',
    partyCardDecision85Number: 'QD85/2020-003',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Vĩnh Long', detail: 'TP. Vĩnh Long' },
    hometown: { country: 'Việt Nam', province: 'Vĩnh Long', detail: 'Bình Minh' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Hưng Lợi' },
    partyAdmissionDate: '03/02/2014',
    officialPartyDate: '03/02/2015',
    oldIdentityNumber: '362000003',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Hồ sơ đầy đủ',
    staffCode: '001003',
    workEmail: 'dangvien03@ctump.edu.vn',
    phone: '0901000003',
    department: 'Bộ môn Ngoại ngữ',
    academicTitle: 'Thạc sĩ, Giảng viên',
    jobTitle: 'Giảng viên chính',
    userUid: 'uid-member-03',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-004',
    stt: 4,
    fullName: 'ĐẢNG VIÊN MẪU 04',
    normalizedName: 'dang vien mau 04',
    gender: 'Nữ',
    dateOfBirth: '25/04/1992',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '2',
    religionName: 'Phật giáo',
    personalId: '089092004004',
    partyCardNumber: '370123450004',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '19/05/2019',
    partyCardDecision85Number: 'QD85/2020-004',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Đồng Tháp', detail: 'TP. Cao Lãnh' },
    hometown: { country: 'Việt Nam', province: 'Đồng Tháp', detail: 'Sa Đéc' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Hòa' },
    partyAdmissionDate: '26/03/2018',
    officialPartyDate: '26/03/2019',
    oldIdentityNumber: '362000004',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Đang làm nghiên cứu sinh ở Nhật Bản',
    staffCode: '001004',
    workEmail: 'dangvien04@ctump.edu.vn',
    phone: '0901000004',
    department: 'Bộ môn Vật lý Y sinh',
    academicTitle: 'Thạc sĩ, Nghiên cứu sinh',
    jobTitle: 'Giảng viên',
    userUid: 'uid-member-04',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-005',
    stt: 5,
    fullName: 'ĐẢNG VIÊN MẪU 05',
    normalizedName: 'dang vien mau 05',
    gender: 'Nam',
    dateOfBirth: '05/12/1996',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089096005005',
    partyCardNumber: '370123450005',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '03/02/2025',
    partyCardDecision85Number: 'QD85/2025-005',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Sóc Trăng', detail: 'TP. Sóc Trăng' },
    hometown: { country: 'Việt Nam', province: 'Sóc Trăng', detail: 'Mỹ Xuyên' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Cái Khát' },
    partyAdmissionDate: '15/09/2025',
    officialPartyDate: undefined, // Dự bị
    oldIdentityNumber: '362000005',
    activityStatus: 'Đang sinh hoạt Đảng',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Đảng viên dự bị (12 tháng)',
    staffCode: '001005',
    workEmail: 'dangvien05@ctump.edu.vn',
    phone: '0901000005',
    department: 'Bộ môn Hóa học Y học',
    academicTitle: 'Thạc sĩ',
    jobTitle: 'Giảng viên tập sự',
    userUid: 'uid-member-05',
    createdAt: '2025-09-15T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pm-006',
    stt: 6,
    fullName: 'ĐẢNG VIÊN MẪU 06',
    normalizedName: 'dang vien mau 06',
    gender: 'Nữ',
    dateOfBirth: '30/01/1975',
    ethnicityId: '1',
    ethnicityName: 'Kinh',
    religionId: '1',
    religionName: 'Không',
    personalId: '089075006006',
    partyCardNumber: '370123450006',
    partyCardIssuer: 'Đảng ủy Trường ĐH Y Dược Cần Thơ',
    partyCardIssueDate: '19/05/2002',
    partyCardDecision85Number: 'QD85/2020-006',
    partyOrganization: 'Chi bộ Khoa học cơ bản',
    birthRegistration: { country: 'Việt Nam', province: 'Hậu Giang', detail: 'TP. Vị Thanh' },
    hometown: { country: 'Việt Nam', province: 'Hậu Giang', detail: 'Long Mỹ' },
    permanentResidence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Khánh' },
    partyAdmissionDate: '19/05/2000',
    officialPartyDate: '19/05/2001',
    oldIdentityNumber: '362000006',
    activityStatus: 'Miễn sinh hoạt',
    activityEndDate: '01/01/2026',
    deleteRequested: false,
    validationResult: 'HỢP LỆ',
    validationDetails: 'Miễn sinh hoạt theo quyết định Chi bộ',
    staffCode: '001006',
    workEmail: 'dangvien06@ctump.edu.vn',
    phone: '0901000006',
    department: 'Bộ môn Tế bào - Mô phôi',
    academicTitle: 'Tiến sĩ',
    jobTitle: 'Giảng viên cao cấp',
    userUid: 'uid-member-06',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_FOREIGN_TRIPS: ForeignTrip[] = [
  {
    id: 'ft-001',
    memberId: 'pm-004',
    memberFullName: 'ĐẢNG VIÊN MẪU 04',
    staffCode: '001004',
    purposes: ['Học tập', 'Nghiên cứu'],
    relativesAbroard: ['Người thân'],
    startDate: '01/10/2025',
    endDate: '30/09/2026',
    destinationCountry: 'Nhật Bản',
    city: 'Tokyo',
    agency: 'Đại học Tokyo (UTokyo)',
    decisionNumber: 'QĐ-CTUMP/2025/104',
    fundingSource: 'Học bổng MEXT',
    details: 'Tham gia chương trình nghiên cứu tiến sĩ chuyên ngành Sinh học phân tử',
    notes: 'Đã báo cáo định kỳ tháng 06/2026',
    attachedFiles: [{ name: 'Quyet_dinh_cu_di_hoc_Japan.pdf', url: '#', size: 1240000 }],
    approvalStatus: 'APPROVED',
    tripStatus: 'ABROAD',
    createdAt: '2025-09-20T08:00:00Z',
    createdBy: 'uid-org-admin',
    updatedAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'ft-002',
    memberId: 'pm-001',
    memberFullName: 'NGUYỄN THỊ THU TRÂM',
    staffCode: '001001',
    purposes: ['Đi công tác'],
    relativesAbroard: [],
    startDate: '10/11/2026',
    endDate: '20/11/2026',
    destinationCountry: 'Pháp',
    city: 'Paris',
    agency: 'Viện Nghiên cứu Y học Quốc gia Pháp (INSERM)',
    decisionNumber: 'QĐ-CTUMP/2026/089',
    fundingSource: 'Ngân sách Đề tài cấp Bộ',
    details: 'Dự hội thảo khoa học quốc tế về Công nghệ gen và Y học dự phòng',
    approvalStatus: 'APPROVED',
    tripStatus: 'UPCOMING',
    createdAt: '2026-07-15T08:00:00Z',
    createdBy: 'uid-admin-01',
    updatedAt: '2026-07-20T08:00:00Z',
  },
  {
    id: 'ft-003',
    memberId: 'pm-003',
    memberFullName: 'TRẦN THỊ HỒNG LÊ',
    staffCode: '001003',
    purposes: ['Công việc riêng'],
    relativesAbroard: ['Cha', 'Mẹ'],
    startDate: '01/06/2025',
    endDate: '15/06/2025',
    destinationCountry: 'Hoa Kỳ',
    city: 'California',
    agency: 'Thăm nhân thân',
    decisionNumber: 'QĐ-CTUMP/2025/042',
    fundingSource: 'Cá nhân tự túc',
    details: 'Thăm cha mẹ và nghỉ phép hàng năm',
    approvalStatus: 'APPROVED',
    tripStatus: 'RETURNED',
    createdAt: '2025-05-10T08:00:00Z',
    createdBy: 'uid-member-03',
    updatedAt: '2025-06-16T08:00:00Z',
  },
];

export const INITIAL_DEVELOPMENT_CANDIDATES: DevelopmentCandidate[] = [
  {
    id: 'cand-001',
    trackingYear: 2026,
    fullName: 'QUẦN CHÚNG MẪU 01',
    normalizedName: 'quan chung mau 01',
    otherName: 'Giảng viên Trẻ',
    dateOfBirth: '12/03/1998',
    birthPlace: 'Thành phố Cần Thơ',
    personalId: '089098007007',
    personalIdDate: '15/05/2021',
    personalIdPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Quận Ninh Kiều' },
    residence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Xuân Khánh' },
    educationLevel: '12/12',
    professionalLevel: 'Thạc sĩ Y học công cộng',
    workplace: 'Chi bộ Khoa học cơ bản - Bộ môn Y sinh học',
    jobTitle: 'Giảng viên',
    email: 'quanchung01@ctump.edu.vn',
    phone: '0902000001',
    trackingStartDate: '01/01/2025',
    stage: 'DOSSIER_COMPLETION', // Đang hoàn thiện hồ sơ
    mentor1: {
      memberId: 'pm-001',
      fullName: 'ĐẢNG VIÊN MẪU 01',
      partyCardNumber: '370123450001',
      jobTitle: 'Trưởng Bộ môn - Bí thư Chi bộ',
      department: 'Bộ môn Toán - Tin',
      email: 'chibokhcb@ctump.edu.vn',
      assignedAt: '02/01/2025',
    },
    mentor2: {
      memberId: 'pm-002',
      fullName: 'ĐẢNG VIÊN MẪU 02',
      partyCardNumber: '370123450002',
      jobTitle: 'Phó Bí thư Chi bộ',
      department: 'Bộ môn Lý luận chính trị',
      email: 'dangvien02@ctump.edu.vn',
      assignedAt: '02/01/2025',
    },
    personalHistories: [
      {
        id: 'th-1',
        fromDate: '09/2016',
        toDate: '06/2022',
        organizationName: 'Trường Đại học Y Dược Cần Thơ',
        role: 'Sinh viên, Lớp trưởng',
        address: 'Số 179 Nguyễn Văn Cừ, An Khánh, Ninh Kiều, Cần Thơ',
        details: 'Tốt nghiệp Bác sĩ Y học dự phòng loại Giỏi',
      },
      {
        id: 'th-2',
        fromDate: '09/2022',
        toDate: 'Nay',
        organizationName: 'Trường Đại học Y Dược Cần Thơ',
        role: 'Giảng viên Khoa KHCB',
        address: 'Cần Thơ',
        details: 'Hoàn thành chương trình Thạc sĩ năm 2024',
      },
    ],
    otherOrganizationHistories: [
      {
        id: 'o-1',
        fromDate: '2022',
        toDate: 'Nay',
        organizationName: 'Đoàn TNCS Hồ Chí Minh Trường ĐH Y Dược Cần Thơ',
        role: 'Ủy viên BCH Đoàn Khoa',
        address: 'Cần Thơ',
        details: 'Được tặng Bằng khen của Tỉnh đoàn Cần Thơ năm 2025',
      },
    ],
    familyMembers: [
      {
        id: 'fm-1',
        relationship: 'Cha',
        fullName: 'NGUYỄN VĂN A (MẪU)',
        birthYear: '1968',
        occupation: 'Cán bộ hưu trí',
        workplace: 'UBND Phường Ninh Kiều, Cần Thơ',
        residence: 'Ninh Kiều, Cần Thơ',
        politicalHistory: 'Chấp hành nghiêm đường lối của Đảng, pháp luật nhà nước',
      },
      {
        id: 'fm-2',
        relationship: 'Mẹ',
        fullName: 'LÊ THỊ B (MẪU)',
        birthYear: '1972',
        occupation: 'Giáo viên cấp 3',
        workplace: 'Trường THPT Chuyên Lý Tự Trọng',
        residence: 'Ninh Kiều, Cần Thơ',
        politicalHistory: 'Không có vấn đề chính trị phức tạp',
      },
    ],
    politicalHistories: [
      {
        id: 'ph-1',
        subject: 'SELF',
        content: 'Xác minh lịch sử bản thân và gia đình phục vụ kết nạp Đảng',
        period: '2025-2026',
        verificationResult: 'Đảm bảo tiêu chuẩn chính trị theo Quy định 208-QĐ/TW',
        verificationAgency: 'Đảng ủy Công an Tỉnh / Cấp ủy địa phương',
        verificationDate: '15/03/2026',
      },
    ],
    mentorReviews: [
      {
        id: 'mr-1',
        mentorUid: 'uid-admin-01',
        mentorName: 'ĐẢNG VIÊN MẪU 01',
        mentorSlot: 1,
        reviewedAt: '30/06/2025',
        quarter: 'Quý II/2025',
        content: 'Nhiệt tình trong công tác, có tinh thần cầu tiến, chuyên môn tốt. Lập trường tư tưởng vững vàng, tin tưởng tuyệt đối vào Đảng.',
      },
      {
        id: 'mr-2',
        mentorUid: 'uid-org-admin',
        mentorName: 'ĐẢNG VIÊN MẪU 02',
        mentorSlot: 2,
        reviewedAt: '30/06/2025',
        quarter: 'Quý II/2025',
        content: 'Gương mẫu trong chấp hành quy chế chuyên môn, có ý thức tổ chức kỷ luật.',
        recommendations: 'Thống nhất đề nghị kết nạp Đảng',
      },
    ],
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'cand-002',
    trackingYear: 2026,
    fullName: 'QUẦN CHÚNG MẪU 02',
    normalizedName: 'quan chung mau 02',
    dateOfBirth: '18/08/1995',
    birthPlace: 'Tỉnh An Giang',
    personalId: '089095008008',
    personalIdDate: '10/10/2022',
    personalIdPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: { country: 'Việt Nam', province: 'An Giang', detail: 'Chợ Mới' },
    residence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường An Khánh' },
    educationLevel: '12/12',
    professionalLevel: 'Thạc sĩ Toán giải tích',
    workplace: 'Bộ môn Toán - Tin',
    jobTitle: 'Giảng viên',
    email: 'quanchung02@ctump.edu.vn',
    phone: '0902000002',
    trackingStartDate: '01/06/2025',
    stage: 'AWARENESS_CLASS', // Đã học lớp nhận thức về Đảng
    mentor1: {
      memberId: 'pm-001',
      fullName: 'ĐẢNG VIÊN MẪU 01',
      partyCardNumber: '370123450001',
      jobTitle: 'Trưởng Bộ môn - Bí thư Chi bộ',
      department: 'Bộ môn Toán - Tin',
      email: 'chibokhcb@ctump.edu.vn',
      assignedAt: '01/06/2025',
    },
    mentor2: {
      memberId: 'pm-003',
      fullName: 'ĐẢNG VIÊN MẪU 03',
      partyCardNumber: '370123450003',
      jobTitle: 'Giảng viên chính',
      department: 'Bộ môn Ngoại ngữ',
      email: 'dangvien03@ctump.edu.vn',
      assignedAt: '01/06/2025',
    },
    personalHistories: [],
    otherOrganizationHistories: [],
    familyMembers: [],
    politicalHistories: [],
    mentorReviews: [],
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'cand-003',
    trackingYear: 2026,
    fullName: 'QUẦN CHÚNG MẪU 03',
    normalizedName: 'quan chung mau 03',
    dateOfBirth: '05/05/2000',
    birthPlace: 'Tỉnh Đồng Tháp',
    personalId: '089000009009',
    personalIdDate: '20/01/2023',
    personalIdPlace: 'Cục Cảnh sát QLHC về TTXH',
    hometown: { country: 'Việt Nam', province: 'Đồng Tháp', detail: 'Sa Đéc' },
    residence: { country: 'Việt Nam', province: 'Cần Thơ', detail: 'Phường Hưng Lợi' },
    educationLevel: '12/12',
    professionalLevel: 'Cử nhân Ngôn ngữ Anh',
    workplace: 'Bộ môn Ngoại ngữ',
    jobTitle: 'Trợ giảng',
    email: 'quanchung03@ctump.edu.vn',
    phone: '0902000003',
    trackingStartDate: '01/01/2026',
    stage: 'TRACKING',
    mentor1: {
      memberId: 'pm-002',
      fullName: 'ĐẢNG VIÊN MẪU 02',
      partyCardNumber: '370123450002',
      jobTitle: 'Phó Bí thư Chi bộ',
      department: 'Bộ môn Lý luận chính trị',
      email: 'dangvien02@ctump.edu.vn',
      assignedAt: '01/01/2026',
    },
    mentor2: {
      memberId: 'pm-003',
      fullName: 'ĐẢNG VIÊN MẪU 03',
      partyCardNumber: '370123450003',
      jobTitle: 'Giảng viên chính',
      department: 'Bộ môn Ngoại ngữ',
      email: 'dangvien03@ctump.edu.vn',
      assignedAt: '01/01/2026',
    },
    personalHistories: [],
    otherOrganizationHistories: [],
    familyMembers: [],
    politicalHistories: [],
    mentorReviews: [],
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_POLICY_VERSIONS: PolicyVersion[] = [
  {
    id: 'pv-01',
    code: '01-HD/TW',
    name: 'Hướng dẫn 01-HD/TW ngày 19/05/2026',
    status: 'CURRENT_ACTIVE',
    effectiveDate: '19/05/2026',
    confirmedByAdmin: true,
    confirmedAt: '2026-05-20T08:00:00Z',
    itemsConfig: [
      {
        code: 'A1',
        order: 1,
        group: 'GROUP_A',
        name: 'Đơn xin vào Đảng',
        description: 'Viết tay, trình bày rõ nhận thức về Đảng và động cơ vào Đảng',
        mandatory: true,
      },
      {
        code: 'A2',
        order: 2,
        group: 'GROUP_A',
        name: 'Lý lịch của người xin vào Đảng',
        description: 'Kê khai trung thực, đầy đủ theo mẫu 2-KNĐ, có xác minh cấp ủy',
        mandatory: true,
      },
      {
        code: 'A3',
        order: 3,
        group: 'GROUP_A',
        name: 'Giấy chứng nhận hoàn thành lớp bồi dưỡng nhận thức về Đảng',
        description: 'Bản chính do Trung tâm chính trị / Đảng ủy cơ sở cấp',
        mandatory: true,
      },
      {
        code: 'B1',
        order: 4,
        group: 'GROUP_B',
        name: 'Bản nhận xét của đoàn thể nơi công tác (Công đoàn / Đoàn Thanh niên)',
        description: 'Nhận xét ưu khuyết điểm và kiến nghị của đoàn thể',
        mandatory: true,
      },
      {
        code: 'B2',
        order: 5,
        group: 'GROUP_B',
        name: 'Phiếu lấy ý kiến nhận xét của chi ủy / nhân dân nơi cư trú',
        description: 'Mẫu 3-KNĐ lấy ý kiến nơi cư trú theo quy định',
        mandatory: true,
      },
      {
        code: 'B3',
        order: 6,
        group: 'GROUP_B',
        name: 'Giấy giới thiệu của 02 đảng viên chính thức được phân công giúp đỡ',
        description: 'Bản nhận xét và giới thiệu của người hướng dẫn 1 và người hướng dẫn 2',
        mandatory: true,
      },
      {
        code: 'C1',
        order: 7,
        group: 'GROUP_C',
        name: 'Nghị quyết giới thiệu đoàn viên ưu tú vào Đảng của Đoàn Thanh niên',
        description: 'Nếu người xin vào Đảng trong độ tuổi đoàn viên',
        mandatory: false,
      },
      {
        code: 'C2',
        order: 8,
        group: 'GROUP_C',
        name: 'Nghị quyết đề nghị kết nạp đảng viên của Chi bộ',
        description: 'Được biểu quyết tại kỳ họp chi bộ đạt từ 2/3 trở lên',
        mandatory: true,
      },
      {
        code: 'C3',
        order: 9,
        group: 'GROUP_C',
        name: 'Kết luận thẩm định tiêu chuẩn chính trị của cấp ủy có thẩm quyền',
        description: 'Kết luận tiêu chuẩn chính trị phục vụ kết nạp Đảng',
        mandatory: true,
      },
    ],
  },
  {
    id: 'pv-208',
    code: '208-QĐ/TW',
    name: 'Quy định 208-QĐ/TW ngày 26/07/2026',
    status: 'CURRENT_ACTIVE',
    effectiveDate: '26/07/2026',
    confirmedByAdmin: true,
    confirmedAt: '2026-07-27T08:00:00Z',
    itemsConfig: [
      {
        code: 'OFF-1',
        order: 1,
        group: 'OFFICIAL_ITEM',
        name: 'Giấy chứng nhận học lớp bồi dưỡng đảng viên mới',
        description: 'Do Đảng ủy cơ sở cấp sau thời gian dự bị',
        mandatory: true,
      },
      {
        code: 'OFF-2',
        order: 2,
        group: 'OFFICIAL_ITEM',
        name: 'Bản tự kiểm điểm của đảng viên dự bị',
        description: 'Tự đánh giá kết quả rèn luyện trong 12 tháng dự bị',
        mandatory: true,
      },
      {
        code: 'OFF-3',
        order: 3,
        group: 'OFFICIAL_ITEM',
        name: 'Bản nhận xét về đảng viên dự bị của đảng viên chính thức hướng dẫn',
        description: 'Nhận xét của đảng viên hướng dẫn về quá trình dự bị',
        mandatory: true,
      },
      {
        code: 'OFF-4',
        order: 4,
        group: 'OFFICIAL_ITEM',
        name: 'Bản tổng hợp nhận xét của đoàn thể nơi làm việc và chi ủy nơi cư trú',
        description: 'Tổng hợp ý kiến các đoàn thể và chi ủy nơi cư trú',
        mandatory: true,
      },
      {
        code: 'OFF-5.1',
        order: 5,
        group: 'OFFICIAL_ITEM',
        name: 'Nghị quyết đề nghị công nhận đảng viên chính thức của Chi bộ',
        description: 'Nghị quyết chi bộ thông qua biểu quyết',
        mandatory: true,
      },
      {
        code: 'OFF-5.2',
        order: 6,
        group: 'OFFICIAL_ITEM',
        name: 'Nghị quyết của Đảng ủy cơ sở / Bộ phận',
        description: 'Nghị quyết cấp ủy cơ sở',
        mandatory: true,
      },
      {
        code: 'OFF-5.3',
        order: 7,
        group: 'OFFICIAL_ITEM',
        name: 'Quyết định công nhận đảng viên chính thức của cấp ủy có thẩm quyền',
        description: 'Quyết định do Ban Thường vụ Đảng ủy ban hành',
        mandatory: true,
      },
      {
        code: 'OFF-5.4',
        order: 8,
        group: 'OFFICIAL_ITEM',
        name: 'Biên bản công bố quyết định tại kỳ sinh hoạt Chi bộ',
        description: 'Theo dõi ngày công bố quyết định',
        mandatory: true,
      },
    ],
  },
  {
    id: 'pv-06',
    code: '06-HD/TW',
    name: 'Hướng dẫn 06-HD/TW ngày 09/06/2025',
    status: 'REPLACED_HISTORICAL',
    replacedHistoryNote: 'Đã được thay thế bởi Hướng dẫn 01-HD/TW ngày 19/05/2026. Lưu tham chiếu lịch sử.',
    effectiveDate: '09/06/2025',
    confirmedByAdmin: true,
    confirmedAt: '2025-06-10T08:00:00Z',
    itemsConfig: [],
  },
];

export const INITIAL_ADMISSION_DOSSIERS: AdmissionDossier[] = [
  {
    id: 'ad-001',
    candidateId: 'cand-001',
    candidateFullName: 'QUẦN CHÚNG MẪU 01',
    candidateEmail: 'quanchung01@ctump.edu.vn',
    requirementsSnapshot: {
      policyVersionId: 'pv-01',
      policyVersionName: 'Hướng dẫn 01-HD/TW ngày 19/05/2026',
      policyCode: '01-HD/TW',
      snapshotAt: '2026-02-01T08:00:00Z',
      items: INITIAL_POLICY_VERSIONS[0].itemsConfig,
    },
    items: INITIAL_POLICY_VERSIONS[0].itemsConfig.map((cfg) => {
      let status: any = 'NEEDS_SUPPLEMENT';
      let reviewComment = '';
      if (cfg.code === 'A1' || cfg.code === 'A3' || cfg.code === 'B3') {
        status = 'VALID';
        reviewComment = 'Đã thẩm định hợp lệ';
      } else if (cfg.code === 'A2') {
        status = 'PENDING_REVIEW';
        reviewComment = 'Đang chờ thẩm định lý lịch';
      }
      return {
        id: `item-${cfg.code}`,
        code: cfg.code,
        order: cfg.order,
        group: cfg.group,
        name: cfg.name,
        description: cfg.description,
        mandatory: cfg.mandatory,
        allowNotApplicable: !cfg.mandatory,
        policyVersionId: 'pv-01',
        status,
        reviewComment,
        reviewedBy: status === 'VALID' ? 'Bí thư Chi bộ' : undefined,
        reviewedAt: status === 'VALID' ? '2026-03-01T08:00:00Z' : undefined,
        files: status !== 'NOT_STARTED' ? [
          {
            id: `f-${cfg.code}-1`,
            originalName: `${cfg.code}_Quanchung_Mau_01.pdf`,
            mimeType: 'application/pdf',
            size: 1540000,
            url: '#',
            uploadedBy: 'quanchung01@ctump.edu.vn',
            uploadedAt: '2026-02-15T08:00:00Z',
            version: 1,
            reviewStatus: status,
          }
        ] : [],
      };
    }),
    itemsGroupA: [],
    itemsGroupB: [],
    itemsGroupC: [],
    progressPercentage: 44,
    overallStatus: 'IN_PROGRESS',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-03-15T08:00:00Z',
  },
];

export const INITIAL_OFFICIALIZATION_DOSSIERS: OfficializationDossier[] = [
  {
    id: 'off-001',
    memberId: 'pm-005',
    memberFullName: 'ĐẢNG VIÊN MẪU 05',
    partyCardNumber: '370123450005',
    provisionalAdmissionDate: '15/09/2025',
    expectedOfficialDate: '15/09/2026',
    dossierDueDate: '15/08/2026',
    votingThresholdsSnapshot: {
      cellThreshold: 'Ít nhất 2/3 đảng viên chính thức đồng ý',
      executiveCommitteeThreshold: 'Ít nhất 2/3 đảng ủy viên đồng ý',
      standingCommitteeThreshold: 'Trên 1/2 thành viên đồng ý',
    },
    requirementsSnapshot: {
      policyVersionId: 'pv-208',
      policyVersionName: 'Quy định 208-QĐ/TW ngày 26/07/2026',
      policyCode: '208-QĐ/TW',
      snapshotAt: '2025-09-15T08:00:00Z',
      items: INITIAL_POLICY_VERSIONS[1].itemsConfig,
    },
    items: INITIAL_POLICY_VERSIONS[1].itemsConfig.map((cfg) => {
      let status: any = 'UPLOADED';
      if (cfg.code === 'OFF-1' || cfg.code === 'OFF-2') {
        status = 'VALID';
      } else if (cfg.code === 'OFF-3') {
        status = 'PENDING_REVIEW';
      } else {
        status = 'NOT_STARTED';
      }
      return {
        id: `off-item-${cfg.code}`,
        code: cfg.code,
        order: cfg.order,
        group: 'OFFICIAL_ITEM',
        name: cfg.name,
        description: cfg.description,
        mandatory: cfg.mandatory,
        allowNotApplicable: false,
        policyVersionId: 'pv-208',
        status,
        files: status !== 'NOT_STARTED' ? [
          {
            id: `off-f-${cfg.code}`,
            originalName: `${cfg.code}_Dangvien_Mau_05.pdf`,
            mimeType: 'application/pdf',
            size: 980000,
            url: '#',
            uploadedBy: 'dangvien05@ctump.edu.vn',
            uploadedAt: '2026-07-01T08:00:00Z',
            version: 1,
            reviewStatus: status,
          }
        ] : [],
      };
    }),
    progressPercentage: 25,
    currentStatus: 'MONITORING',
    createdAt: '2025-09-15T08:00:00Z',
    updatedAt: '2026-07-01T08:00:00Z',
  },
];

export const INITIAL_CHANGE_REQUESTS: MemberChangeRequest[] = [
  {
    id: 'cr-001',
    memberId: 'pm-003',
    memberFullName: 'ĐẢNG VIÊN MẪU 03',
    requestedByUid: 'uid-member-03',
    requestedByEmail: 'dangvien03@ctump.edu.vn',
    requestedAt: '2026-07-25T09:30:00Z',
    beforeData: { academicTitle: 'Thạc sĩ, Giảng viên', phone: '0901000003' },
    requestedData: { academicTitle: 'Thạc sĩ, Giảng viên chính', phone: '0909999003' },
    changedFields: ['academicTitle', 'phone'],
    reason: 'Cập nhật chức danh sau khi có quyết định bổ nhiệm và thay đổi số điện thoại cá nhân mới.',
    status: 'PENDING',
  },
];

export const INITIAL_USER_ACCOUNTS: UserAccount[] = [
  {
    uid: 'uid-admin-system',
    email: 'chibokhcb@ctump.edu.vn',
    fullName: 'BÍ THƯ CHI BỘ (QUẢN TRỊ HỆ THỐNG)',
    role: 'SUPER_ADMIN',
    positionTitle: 'Bí thư Chi bộ / Email Quản trị',
    staffCode: '001000',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    approvalNotes: 'Quản trị hệ thống toàn quyền',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-bi-thu-tram',
    email: 'ntttram@ctump.edu.vn',
    fullName: 'NGUYỄN THỊ THU TRÂM',
    role: 'SUPER_ADMIN',
    positionTitle: 'Bí thư Chi bộ',
    staffCode: '001001',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    approvalNotes: 'Quản trị tất cả (Toàn quyền Bí thư)',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pho-bi-thu-hung',
    email: 'nthung@ctump.edu.vn',
    fullName: 'NGUYỄN THANH HÙNG',
    role: 'SUPER_ADMIN',
    positionTitle: 'Phó Bí thư Chi bộ',
    staffCode: '001002',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    approvalNotes: 'Quản trị viên Chi ủy (Toàn quyền Thêm, Sửa, Xóa)',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-chi-uy-vien-le',
    email: 'letran@ctump.edu.vn',
    fullName: 'TRẦN THỊ HỒNG LÊ',
    role: 'SUPER_ADMIN',
    positionTitle: 'Chi ủy viên',
    staffCode: '001003',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    approvalNotes: 'Quản trị viên Chi ủy (Toàn quyền Thêm, Sửa, Xóa)',
    createdAt: '2026-01-01T00:00:00Z',
  },
  // Danh sách Đảng viên Chi bộ Khoa học cơ bản (25 Đảng viên)
  {
    uid: 'uid-pm-nttminh',
    email: 'nttminh@ctump.edu.vn',
    fullName: 'NGUYỄN THỊ TUYẾT MINH',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001005',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-lttmy',
    email: 'lttmy@ctump.edu.vn',
    fullName: 'LÝ THỊ TRÀ MY',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001006',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nlmdang',
    email: 'nlmdang@ctump.edu.vn',
    fullName: 'NGUYỄN LÂM MINH ĐĂNG',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001007',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-tttchau',
    email: 'tttchau@ctump.edu.vn',
    fullName: 'TRƯƠNG THỊ TUYẾT CHÂU',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001008',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nptai',
    email: 'nptai@ctump.edu.vn',
    fullName: 'NGUYỄN PHƯỚC TÀI',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001009',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-ptnnga',
    email: 'ptnnga@ctump.edu.vn',
    fullName: 'PHẠM THỊ NGỌC NGA',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001010',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-ltttien',
    email: 'ltttien@ctump.edu.vn',
    fullName: 'LÂM THỊ THỦY TIÊN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001011',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-cmkhoa',
    email: 'cmkhoa@ctump.edu.vn',
    fullName: 'CHÂU MINH KHOA',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001012',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-lththanh',
    email: 'lththanh@ctump.edu.vn',
    fullName: 'LƯƠNG THỊ HOÀI THANH',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001013',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nhthai',
    email: 'nhthai@ctump.edu.vn',
    fullName: 'NGUYỄN HOÀNG THÁI',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001014',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-axsam',
    email: 'axsam@ctump.edu.vn',
    fullName: 'ÂU XUÂN SÂM',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001015',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-dqthanh',
    email: 'dqthanh@ctump.edu.vn',
    fullName: 'DƯƠNG QUỐC THANH',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001016',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-dtttran',
    email: 'dtttran@ctump.edu.vn',
    fullName: 'ĐOÀN THỊ THÙY TRÂN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001017',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nxvinh',
    email: 'nxvinh@ctump.edu.vn',
    fullName: 'NGUYỄN XUÂN VINH',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001018',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-dntruong',
    email: 'dntruong@ctump.edu.vn',
    fullName: 'ĐINH NGỌC TRƯỜNG',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001019',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nnuyen',
    email: 'nnuyen@ctump.edu.vn',
    fullName: 'NGÔ NGỌC UYÊN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001020',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-vttrinh',
    email: 'vttrinh@ctump.edu.vn',
    fullName: 'VÕ THÀNH TRINH',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001021',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-lmthuan',
    email: '2453110046@student.ctump.edu.vn',
    fullName: 'LÊ MINH THUẬN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên / Sinh viên',
    staffCode: '2453110046',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-dntdat',
    email: '2453110009@student.ctump.edu.vn',
    fullName: 'ĐỖ NGUYỄN TIẾN ĐẠT',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên / Sinh viên',
    staffCode: '2453110009',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-lmnhan',
    email: 'lmnhan@ctump.edu.vn',
    fullName: 'LÊ MINH NHÂN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001024',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nhmen',
    email: 'nhmen@ctump.edu.vn',
    fullName: 'NGUYỄN HOÀNG MẾN',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001025',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-dntduong',
    email: '2553110010@student.ctump.edu.vn',
    fullName: 'DƯƠNG NGỌC THÙY DƯƠNG',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên / Sinh viên',
    staffCode: '2553110010',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-ltnhi',
    email: 'ltnhi@ctump.edu.vn',
    fullName: 'LÝ TUYẾT NHI',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001027',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-ltde',
    email: 'ltde@ctump.edu.vn',
    fullName: 'LÊ TIỀN ĐỀ',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001028',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    uid: 'uid-pm-nhpdai',
    email: 'nhpdai@ctump.edu.vn',
    fullName: 'NGUYỄN HỮU PHƯỚC ĐẠI',
    role: 'PARTY_MEMBER',
    positionTitle: 'Đảng viên',
    staffCode: '001029',
    status: 'ACTIVE',
    requiresSecretaryApproval: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    actorUid: 'uid-admin-01',
    actorEmail: 'chibokhcb@ctump.edu.vn',
    performedByEmail: 'chibokhcb@ctump.edu.vn',
    action: 'SYSTEM_BOOTSTRAP',
    resourceType: 'SYSTEM',
    targetCollection: 'SYSTEM',
    resourceId: 'root',
    targetId: 'root',
    timestamp: '2026-08-01T08:00:00Z',
    performedAt: '2026-08-01T08:00:00Z',
    requestId: 'req-001',
    maskedSummary: 'Khởi tạo hệ thống thành công với dữ liệu ẩn danh Chi bộ Khoa học cơ bản',
    details: 'Khởi tạo hệ thống thành công với dữ liệu ẩn danh Chi bộ Khoa học cơ bản',
  },
  {
    id: 'log-002',
    actorUid: 'uid-member-03',
    actorEmail: 'dangvien03@ctump.edu.vn',
    performedByEmail: 'dangvien03@ctump.edu.vn',
    action: 'CREATE_CHANGE_REQUEST',
    resourceType: 'MEMBER_CHANGE_REQUEST',
    targetCollection: 'MEMBER_CHANGE_REQUEST',
    resourceId: 'cr-001',
    targetId: 'cr-001',
    timestamp: '2026-07-25T09:30:00Z',
    performedAt: '2026-07-25T09:30:00Z',
    requestId: 'req-002',
    maskedSummary: 'Tạo đề nghị cập nhật hồ sơ cá nhân (thay đổi chức danh & SĐT)',
    details: 'Tạo đề nghị cập nhật hồ sơ cá nhân (thay đổi chức danh & SĐT)',
  },
];

export const INITIAL_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'tmpl-01',
    templateCode: 'MAU-01-KND',
    title: 'Đơn xin vào Đảng (Viết tay mẫu)',
    category: 'Kết nạp Đảng',
    policyVersionId: 'pv-01',
    fileUrl: '#',
    originalName: 'Don_xin_vao_Dang_Mau_2026.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    version: 1,
    isActive: true,
    uploadedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-02',
    templateCode: 'MAU-02-KND',
    title: 'Lý lịch của người xin vào Đảng',
    category: 'Kết nạp Đảng',
    policyVersionId: 'pv-01',
    fileUrl: '#',
    originalName: 'Ly_lich_nguoi_xin_vao_Dang_Mau_2026.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    version: 1,
    isActive: true,
    uploadedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'tmpl-03',
    templateCode: 'MAU-03-OFF',
    title: 'Bản tự kiểm điểm đảng viên dự bị',
    category: 'Công nhận chính thức',
    policyVersionId: 'pv-208',
    fileUrl: '#',
    originalName: 'Ban_tu_kiem_diem_dang_vien_du_bi.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    version: 1,
    isActive: true,
    uploadedAt: '2026-01-10T08:00:00Z',
  },
];
